### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by clnsdzy** [bbonugba/Recipe.com#1]
Kindly preview the minor fixes below and implement them on your project:

- [x] Edit the 'Customer's' in the nav elements to 'Customers'
- [x] Use the `flow-text` class for all p tags to make it responsive on all screen sizes.
- [x] The Cakes title is not `orange-text text-darken-4`. Correct it, please.
- [x] Reduce the text content in each Card to a minimum of two lines.
- [x] Convert your name in the copyright section to a link that redirects to your GitHub profile.
- [x] The sidenav trigger has an orange background. Remove it.
The parallax effect does not work on mobile devices. Use the M.css hide classes to: 
- [x] make the parallax component visible only on desktop devices
- [x] and a responsive image (of the same picture as the corresponding parallax) to show on tablets and smartphones

After implementing any of the changes above, click on the checkbox to indicate completion. When you're done completely, mark this Issue as done

**Comment by bbonugba** [comment]
I'm not exactly sure oof what I did on the last part but all other issues have been fixed!

**Comment by clnsdzy** [comment]
> I'm not exactly sure oof what I did on the last part but all other issues have been fixed!

You can do it 👍🏾
